server:
  port: 4000

spring:
  application:
    name: counters

#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Eureka Properties  
# ==============================================================
eureka:
   client:
    registerWithEureka: true
    #fetchRegistry: true
    serviceUrl:
     defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/} 