#docker-compose up
version: '3.3'

networks: 
  ntpgsql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
  rabbitntw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

services:
  pgsql:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgresql
    volumes: 
      - psdb-volume:/var/lib/postgresql/data
    networks: 
      ntpgsql:
        ipv4_address: 172.21.0.2
    ports:
      - target: 5432
        published: 5433 
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_PASSWORD=123_Stella
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin4
  
    networks:
      ntpgsql:
        ipv4_address: 172.21.0.3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_DEFAULT_EMAIL=caparvi.2014215@studenti.uniroma1.it
      - PGADMIN_DEFAULT_PASSWORD=123_Stella

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: rabbitmq
    networks: 
      rabbitntw:
        ipv4_address: 172.25.0.2
    ports:
        #porta container
      - target: 5672
        published: 5672 
        protocol: tcp
        mode: host
        #porta interfaccia web
      - target: 15672
        published: 15672 
        protocol: tcp
        mode: host
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
  zipkin:
    image: openzipkin/zipkin
    restart: unless-stopped
    container_name: zipkin
    networks: 
      rabbitntw:
        ipv4_address: 172.25.0.5
    ports:
      - target: 9411
        published: 9411 
        protocol: tcp
        mode: host
    environment:
      - RABBIT_ADDRESSES=172.25.0.2
      - STORAGE_TYPE=mem
      - RABBIT_USER=rabbitmq
      - RABBIT_PASSWORD=rabbitmq
    depends_on:
      - rabbitmq

  
volumes:
  psdb-volume:
  rabbitmq-volume:

