server:
  port: 5000

spring:
  application:
    name: counters

#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    #password: ${RDS_PASSWORD:123_Stella}
    password: 123_Stella
    url: jdbc:postgresql://${RDS_HOSTNAME:192.168.51.5}:5432/postgres #${RDS_DB_NAME:CovidCounter}
    #url: jdbc:postgresql://localhost:5433/postgres

    #username: ${RDS_USERNAME:postgres}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Opzioni Open Feign  
# ==============================================================
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
